sudo: false
language: python

notifications:
  email: false

env:
  - PYTHONDONTWRITEBYTECODE=1

python:
  - "2.7"

install:
  - pip install ${PIP_OPTS} pkgstack

script:
  - pkgstack --profile conf/packages.yml --stage test
  - pip install --editable .
  - make test-all-with-coverage

after_success:
  - codecov
